CLASS cl_testsuite DEFINITION PUBLIC CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS run.
ENDCLASS.


CLASS cl_testsuite IMPLEMENTATION.

  METHOD run.
    WRITE / 'todo test'.
  ENDMETHOD.

ENDCLASS.
