CLASS zcl_wasm_perf_i32_store DEFINITION PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS run RAISING zcx_wasm.
ENDCLASS.

CLASS zcl_wasm_perf_i32_store IMPLEMENTATION.

  METHOD run.
  ENDMETHOD.

ENDCLASS.
