name: regression

on: pull_request

permissions:
  contents: read

jobs:
  regression:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/setup-node@v4

    - uses: actions/checkout@v4
    - run: npm ci && npm test
    - run: cp web/totals.json ../after.json

    - uses: actions/checkout@v4
      with:
        ref: 'main'
    - run: npm ci && npm test
    - run: cp web/totals.json ../before.json

    - run: ls -l ../
    - run: node test/build_comment.mjs