name: regression

on: pull_request

permissions:
  contents: read

jobs:
  regression:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm test
    - run: ls -l web

    - uses: actions/checkout@v4
      with:
        ref: 'main'
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm test
    - run: ls -l web