name: regression

on: pull_request

permissions:
  contents: read

jobs:
  regression:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/setup-node@v4

    - uses: actions/checkout@v4
      with:
        ref: 'main'
    - run: npm ci && npm test
    - run: cp web/totals.json ../before.json

    - uses: actions/checkout@v4
    - run: npm ci && npm test
    - run: cp web/totals.json ../after.json

    - run: node test/build_comment.mjs

    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.findPr.outputs.pr }}

    - name: Find Comment
      if: steps.findPr.outputs.pr != ''
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: '${{steps.findPr.outputs.pr}}'
        body-includes: Regression test results

    - run: echo ${{ steps.fc.outputs.comment-id }}

    - name: Create comment
      if: steps.findPr.outputs.pr != ''
      uses: peter-evans/create-or-update-comment@v3
      id: create-comment
      with:
        issue-number: '${{steps.findPr.outputs.pr}}'
        edit-mode: replace
        comment-id: '${{steps.fc.outputs.comment-id}}'
        body-path: ./comment-regression.txt