name: unittest

on: [push, pull_request]

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: npm run downport
      run: npm run downport
    - name: npm run unit
      run: npm run unit
