name: test

on: pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm test
    - name: Upload build artifact
      uses: actions/upload-artifact@main
      with:
        name: testsuite.html
        path: ./web/testsuite.html
        retention-days: 7